spring.application.name=PatentManagement2

spring.datasource.url=jdbc:postgresql://localhost:5432/PatentManagement2
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
